import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { SignInButton } from "@clerk/nextjs";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>a dip with T3</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className=" mx-auto w-5/6 rounded-xl bg-slate-500">
        <div className="mt-2 h-1/5 min-h-min">
          <h1 className=" py-4 text-center">HOMEPAGE</h1>
          <div className=" customBtns mx-auto grid w-1/2 grid-cols-2 gap-4">
            <Link
              href={`/sign-up`}
              className=" col-span-1 mb-2 rounded-sm bg-red-400 px-2 py-3 text-center"
            >
              Sign Up
            </Link>
            <Link
              href={`/sign-in`}
              className=" col-span-1 mb-2 rounded-sm bg-red-400 px-2 py-3 text-center"
            >
              Sign In
            </Link>
          </div>
          {/* <div className=" clerkBtns mx-auto grid w-1/2 grid-cols-2 gap-4">
            <SignInButton />
          </div> */}
        </div>
      </main>
    </>
  );
};

export default Home;
